name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Capacitor APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Sync Capacitor Android Project
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        working-directory: ./android
        run: chmod +x gradlew

      - name: Build APK File
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Upload APK so you can download it
        uses: actions/upload-artifact@v4
        with:
          name: Invoeazy-App-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
